"""empty message

Revision ID: b7c7a411e112
Revises: 11d13a94b507
Create Date: 2023-08-08 21:51:53.247649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c7a411e112'
down_revision = '11d13a94b507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('move_assistance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('move_assistance', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
