"""empty message

Revision ID: e61e309d2438
Revises: fe4d7fd6595f
Create Date: 2023-08-09 11:54:49.672537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61e309d2438'
down_revision = 'fe4d7fd6595f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('move_assistance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('move_assistance', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
